/* ══════════ VANDERBILT VOYAGE ONLINE · narration ══════════
   One script per page, keyed by the pager's <section>/<n>, plus one short
   clip per lesson card, timeline moment, belief, moment, compass result,
   and situation (welcome/g1, history/g1, beliefs/t1, beliefs/m1,
   compass/growth, grow/s1). The Listen button plays
   assets/audio/voyage/<key with / as ->.mp3, recorded from these exact
   words by scripts/build-tts.py, and falls back to the browser's speech
   synthesis when a clip is missing. Names are spelled as they are said
   (Diermeier is written Deer-myer, said DEER-my-er; the motto Crescere aude
   is written Kresh-eh-ray ow-day); the screen keeps the real spelling. Plain language: where you are, why it
   matters, what to do on this page, what is next. No em or en dashes. */
window.VVO_NARR = {
  'home/1': 'Welcome to the start of your Vanderbilt Voyage. We are thrilled to have you aboard as you begin this new chapter in your career. Today is day one, and we cannot wait to get to know you and to see the work you will do here. This course takes about thirty minutes, in six short lessons. By the end, you will be able to name the four beliefs that guide Vanderbilt, explain how each one contributes to Vanderbilt’s culture and the employee experience, apply them to real moments in your day, explore ways to partner with colleagues and find opportunities to collaborate, identify the resources that support your connection, growth, and career development, and plan the conversation with your manager that starts your development plan. Each page has one idea and one thing to do. Turn pages with the arrows at the bottom right, and tap Listen on any page to hear it again. When you are ready, tap Begin the voyage. First up, a welcome from the Chancellor.',
  'mission/1': 'Now, our mission, because everything in this course connects back to it. Vanderbilt will define the great university of the twenty-first century, and be it. To get there, Vanderbilt operates at uncommon speed, agility, and scale, with three areas of focus. The first is Exceptional Core Operations: the talent, resources, and reputation to deliver on the vision. The second is Bold Strategic Initiatives: with core operations as the fuel, bolder initiatives that extend the reach of our education and research mission. The third is Values Leadership: advocating for, and modeling, the role of an essential research university. So where do you come in? Whatever your role, the mission is achieved through the work you do. Know it. Connect your work to it. And stay in touch with your manager about priorities, projects, and how you are settling in. Tap each area of focus to read it in full.',
  'press/1': 'Vanderbilt’s growth is making news. In August twenty twenty six, New York City opened in Chelsea, our first campus beyond Nashville, and the Chancellor rang the Nasdaq opening bell to celebrate. San Francisco opens for the twenty twenty seven to twenty eight academic year, home to the Huang College of Art, Architecture and Design. West Palm Beach is taking shape as a graduate campus for business, engineering, data science, and A I. And in July, Vanderbilt and EPB launched the Institute for Quantum Innovation in Chattanooga, with about two hundred fifty researchers, faculty, and staff. Use the buttons to filter by campus, and tap any story to read it in full.',
  'mission/f1': 'Area of focus one. Exceptional core operations. With speed, agility, and scale, Vanderbilt will distinguish itself with innovative and impactful capabilities, so we have the talent, resources, and reputation we need to deliver on our vision.',
  'mission/f2': 'Area of focus two. Bold strategic initiatives. With exceptional core operations as our fuel, Vanderbilt will pursue increasingly bold initiatives that enable and enhance the reach and impact of our education and research mission.',
  'mission/f3': 'Area of focus three. Values leadership. Through strategic advocacy, and by modeling the role of an essential research university, Vanderbilt will stimulate industry change and combat existential threats to our education and research mission.',
  'cities/1': 'And we are growing, on purpose. Vanderbilt now works from five cities, as one network university, and we are not copying Nashville in each one. Each city puts Vanderbilt where a field leads: business and technology in New York City, business, engineering, and A I in West Palm Beach, art, design, and technology in San Francisco, and quantum science at the Quantum Campus in Chattanooga, with Nashville as our home. Tap each campus on the map to see why we are there. The same mission and beliefs travel with us, wherever you sit.',
  'welcome/1': 'Lesson one. Welcome to the Vanderbilt Voyage. Start with the video: a welcome from Chancellor Daniel Deer-myer. His vision, daring to grow, is the thread through everything that follows. Then explore the route. Six short lessons: welcome and our mission, our history and leadership, Vanderbilt by the numbers, the four beliefs, dare to grow, and your next steps. Tap each stop to preview it.',
  'welcome/g1': 'Lesson one is where you are now: a welcome from the Chancellor, then our mission and the five cities Vanderbilt works from.',
  'welcome/g2': 'Lesson two is our history and leadership. More than one hundred and fifty years of daring to grow, a short timeline, and the people who lead Vanderbilt today: Chancellor Daniel Deer-myer and the vice chancellors.',
  'welcome/g3': 'Lesson three is our mission, our students, and you. Seven numbers that put the mission in perspective, a campus fun fact, and Vanderbilt quick facts.',
  'welcome/g4': 'Lesson four is the heart of the course: the four beliefs. Belonging, self-direction, collaboration, and growth. You will explore each one, practice it, and then use the belief compass to find the one that fits you best.',
  'welcome/g5': 'Lesson five is dare to grow. Our motto, Kresh-eh-ray ow-day, and what it means as a mindset, with three situations to try it.',
  'welcome/g6': 'Lesson six is next steps. A short check of what you learned, four commitments, including a conversation with your manager, and an open invitation to visit us in Nashville.',
  'history/1': 'Lesson two. Our history. For more than one hundred and fifty years, Vanderbilt has been blazing trails, making transformative discoveries, and leading boldly. Start with the video, and watch our history come alive. Then walk the timeline below it: twelve moments from the Commodore’s gift in eighteen seventy three to today. Tap a year to hear its story, or press Play the timeline. When you want more, open the full history.',
  'history/t1': 'Eighteen seventy three. In his seventy ninth year, Cornelius Vanderbilt, known as the Commodore, gives one million dollars to build a university in the South that would contribute to strengthening the ties between all sections of our common country.',
  'history/t2': 'Eighteen seventy five. Bishop Holland McTyeire chose the site and planted many of the trees that make Vanderbilt an arboretum today. The university opens with one Main Building, now Kirkland Hall, an observatory, and three hundred and seven students.',
  'history/t3': 'Eighteen ninety three. James Kirkland becomes chancellor and leads for forty four years, the longest in Vanderbilt history. After a fire in nineteen oh five consumes the Main Building, he rebuilds, and the building is later renamed in his honor.',
  'history/t4': 'Nineteen thirteen. At least one woman attended Vanderbilt classes every year from eighteen seventy five. By nineteen thirteen, seventy eight women make up just over twenty percent of the academic enrollment.',
  'history/t5': 'Nineteen fourteen. The Board of Trust severs ties with the Methodist Episcopal Church, South, after a dispute over who would appoint the university’s trustees. Vanderbilt charts its own course.',
  'history/t6': 'Nineteen forty nine. Vanderbilt is elected to the Association of American Universities, a mark of national recognition.',
  'history/t7': 'Nineteen sixty three. At its ninetieth anniversary, Vanderbilt ranks among the top twenty private universities for the first time. Chancellor Alexander Heard goes on to add Blair, the Owen Graduate School of Management, and Peabody College.',
  'history/t8': 'Two thousand. Under Chancellor Gordon Gee, Vanderbilt leads the country in the growth rate of research funding and becomes one of the most selective universities in the nation.',
  'history/t9': 'Two thousand eight. Chancellor Nicholas Zeppos launches Opportunity Vanderbilt, loan-free aid for the most deserving students, opens Martha Ingram Commons, the start of the residential colleges, and begins FutureVU.',
  'history/t10': 'Twenty sixteen. Vanderbilt University and Vanderbilt University Medical Center separate, positioning both for long-term success, and they keep working closely together.',
  'history/t11': 'Twenty twenty. Daniel Deer-myer becomes the ninth chancellor on July first. He guides Vanderbilt through the pandemic and launches Destination Vanderbilt and the Vanderbilt Project on Unity and American Democracy.',
  'history/t12': 'And today. Vanderbilt is a private research university with more than seven thousand three hundred undergraduates, more than six thousand two hundred graduate and professional students, and twelve schools and colleges, working from Nashville and four more cities.',
  'leaders/1': 'Still in lesson two: our leadership. Daniel Deer-myer became Vanderbilt’s ninth chancellor on July first, twenty twenty. He is an internationally renowned scholar of political science and managerial leadership. Born in Berlin, and the first in his family to graduate from college, he was provost of the University of Chicago, and a longtime professor at Stanford and at Northwestern’s Kellogg School, before Vanderbilt’s Board of Trust chose him after a worldwide search. He guided Vanderbilt through the pandemic, launched Destination Vanderbilt to recruit renowned faculty, and saw research pass one billion dollars. He leads with a team of vice chancellors, each responsible for a part of the university: academic affairs, communications, government relations, investments, athletics, development, operations, facilities, people, culture and belonging, Vanderbilt Enterprises, and general counsel. Now try four statements. Fact, or fiction?',
  'numbers/1': 'Lesson three. Our mission, our students, and you. Vanderbilt’s rankings are important. But we are even more impressed by numbers like these, because they show the community you just joined, and the work that keeps it running. Seven tiles. Tap one, make your best guess, and see the real number. Guessing first is what makes it stick. The last tile is a fun fact about some of our smallest, furriest neighbors. The next page has the rest of the quick facts.',
  'facts/1': 'Still in lesson three: a quick scavenger hunt. Tap Launch Vanderbilt Quick Facts. It opens in a new tab. Then answer eight questions, one from each part of the page: students, campus, academics, undergraduate life, research, faculty, affordability, and life after Vanderbilt. Each number you find lights up a tile on your board. Last, tell us which fact surprised you most. Your answers print with your Voyage summary at the end of the course.',
  'beliefs/1': 'Lesson four. The four beliefs and the Vanderbilt Way. At Vanderbilt we offer more than an education: a journey of exceptional learning, opportunity, and experience. Four core beliefs guide it: belonging, self-direction, collaboration, and growth. They also guide how we work together. Tap each point on the compass to see the belief and the behaviors that show it, then try it in a short moment. After all four, turn the page for your belief compass.',
  'beliefs/t1': 'Belonging. Once you’re chosen, you belong. Vanderbilt is intentionally very selective, and only people with the highest potential make the cut. Once you are here, you are surrounded by the best and brightest, brought together for one simple purpose: to improve each other. The behaviors: confident, never cutthroat. When you join, you commit. Respect the Vanderbilt Way. Create and cultivate conditions for success. Celebrate differences. And foster unity.',
  'beliefs/t2': 'Self-direction. Choose your own path, and go all in. Personal purpose is found through relentless exploration and challenge. If it is too comfortable, you are not doing it right. Experience as much as you can, and once you discover your path, give it everything you have. The behaviors: try, fail, learn, repeat. Embrace discomfort. Be ready to change your mind. Put in the work. No shortcuts. And prove the doubters wrong.',
  'beliefs/t3': 'Collaboration. Teams challenge and support each other. Our goal as a community is to work as one. By challenging and supporting one another, high functioning teams accomplish far more than individuals, and only by rallying around a common purpose can we multiply our individual potential. The behaviors: bands do more than soloists. Ditch the ego. See no boundaries. Pioneer together. Challenge directly. Respect the person. And redefine possible.',
  'beliefs/t4': 'Growth. We never stop growing and achieving. A permanent growth mindset matters more than any single achievement, however big. Human potential is realized over a lifetime, in increments and leaps, and it expands as you grow. The behaviors: growing the whole person. Obsessive self-improvement. In competition with yourself. Be the ladder for others. And lifelong leveling up.',
  'beliefs/m1': 'Here is a moment for belonging. It is your second week. In the team meeting, a colleague shares an idea that is quite different from how you would approach the problem, and the room goes quiet. What do you do?',
  'beliefs/m2': 'A moment for self-direction. Your manager asks who wants to lead a small project using a system nobody on the team knows well, including you. It would stretch you, and it would be uncomfortable. What do you do?',
  'beliefs/m3': 'A moment for collaboration. Someone from another department asks for help with a problem that is not technically your team’s job. You have the knowledge to help, and a busy week. What do you do?',
  'beliefs/m4': 'A moment for growth. You get feedback on your first project: the work is solid, and the way you presented it was hard to follow. It stings a little. What do you do?',
  'compass/1': 'Still in lesson four: your belief compass. You will live all four beliefs here. This page helps you find the one that sounds most like you right now. Four questions, one at a time, and there are no wrong answers. Pick the answer that fits you best, and watch the needle find your belief. Then write one sentence about how you will show it at work. You will bring that to your manager in lesson six.',
  'compass/belonging': 'Your compass points to belonging. Once you’re chosen, you belong. You care about the people around you, and about making Vanderbilt feel like home for everyone. Start with two behaviors: confident, never cutthroat, and when you join, you commit.',
  'compass/selfdir': 'Your compass points to self-direction. Choose your own path, and go all in. You are drawn to the challenge, and you finish what you choose. Start with two behaviors: try, fail, learn, repeat, and embrace discomfort.',
  'compass/collab': 'Your compass points to collaboration. Teams challenge and support each other. You do your best work with other people. Start with two behaviors: bands do more than soloists, and ditch the ego.',
  'compass/growth': 'Your compass points to growth. We never stop growing and achieving. You measure yourself against who you were yesterday. Start with two behaviors: growing the whole person, and obsessive self-improvement.',
  'grow/1': 'Lesson five. Dare to grow. Vanderbilt’s motto is Kresh-eh-ray ow-day, Latin for dare to grow. It is more than a motto; it is a mindset. Adopt a growth mindset, because ability grows with effort. Use what is here: mentors, programs, courses, and your manager. And grow together, because growth at Vanderbilt is a team sport. Watch the short video, then try three situations. Pick the response you would give, then try the other two.',
  'grow/s1': 'Situation one. Your team uses a system you have never seen. Everyone else moves through it fast, and you have a report due in it on Friday. What do you do?',
  'grow/s2': 'Situation two. You sent an email to the wrong list. It is not a disaster, but a few people noticed. What do you do?',
  'grow/s3': 'Situation three. A colleague who started a month after you is stuck on something you figured out last week. What do you do?',
  'quiz/1': 'Lesson six begins with a quick check. Five questions, one at a time. Four of five finishes the check, and you can retake it anytime. Each answer tells you why.',
  'nextstep/1': 'Now, your next steps. We covered a lot in this course, and there is more to do. These tasks lock in what you learned and set you up for what comes next. Tap each one to commit. Discuss with your manager which belief you align with most, and how it will guide how you show up to work. Work with your manager to put your development plan into action. Complete your required compliance education. And finish your other tasks, including the Benefits Information Course and the Vanderbilt Voyage Day One Survey. Then copy the message to your manager, and send it today. It already includes the belief your compass found. And if you are ever in Nashville, join us for the full in-person Voyage, a campus tour, or just lunch. Email People, Culture and Belonging at p c b at vanderbilt dot e d u.',
  'learn/1': 'That is the course. Thank you for your attention, and welcome to Vanderbilt. The links from every lesson are on this page, to come back to in your first weeks. Take the Vanderbilt Voyage Day One Survey before you go. And remember, daring to grow is a powerful step toward your full potential. Kresh-eh-ray ow-day.'
};
