/* ══════════ VANDERBILT VOYAGE ONLINE · narration ══════════
   One script per page, keyed by the pager's <section>/<n>, plus one short
   clip per lesson card, timeline moment, belief, moment, compass result,
   and situation (welcome/g1, history/g1, beliefs/t1, beliefs/m1,
   compass/growth, grow/s1). The Listen button plays
   assets/audio/voyage/<key with / as ->.mp3, recorded from these exact
   words by scripts/build-tts.py, and falls back to the browser's speech
   synthesis when a clip is missing. Plain language: where you are, why it
   matters, what to do on this page, what is next. No em or en dashes. */
window.VVO_NARR = {
  'home/1': 'Welcome to the start of your Vanderbilt Voyage. We are thrilled to have you aboard as you begin this new chapter in your career. Today is day one, and we cannot wait to get to know you and to see the work you will do here. This course takes about thirty minutes, in six short lessons. By the end, you will be able to name the four beliefs that guide Vanderbilt, explain how each one contributes to Vanderbilt’s culture and the employee experience, apply them to real moments in your day, explore ways to partner with colleagues and find opportunities to collaborate, identify the resources that support your connection, growth, and career development, and plan the conversation with your manager that starts your development plan. Turn pages with the arrows at the bottom right. Tap Listen on any page, or turn on Auto to hear every page as it turns. Let’s set sail.',
  'mission/1': 'First, our mission, because everything in this course connects back to it. Vanderbilt will define the great university of the twenty-first century, and be it. To get there, Vanderbilt operates at uncommon speed, agility, and scale, with three areas of focus. The first is Exceptional Core Operations: the talent, resources, and reputation to deliver on the vision. The second is Bold Strategic Initiatives: with core operations as the fuel, bolder initiatives that extend the reach of our education and research mission. The third is Values Leadership: advocating for, and modeling, the role of an essential research university. And we are growing. Vanderbilt now works from five cities: Nashville, our home, plus Chattanooga, New York City, West Palm Beach, and San Francisco. The same mission and beliefs travel with us, wherever you sit. So where do you come in? Whatever your role, the mission is achieved through the work you do. Know it. Connect your work to it. And stay in touch with your manager about priorities, projects, and how you are settling in.',
  'welcome/1': 'Lesson one. Welcome to the Vanderbilt Voyage. Here is the route for this course: six lessons. Welcome. Our history and leadership. Our mission, our students, and you. The four beliefs and the Vanderbilt Way. Dare to grow. And next steps. Tap each lesson card to open it and hear what is inside. Below the cards is a message to start from Chancellor Daniel Diermeier. His vision, daring to grow, is the thread through everything that follows.',
  'welcome/g1': 'Lesson one is where you are now. It covers what this course is about, the Chancellor’s vision for Vanderbilt, and how to get the most from your first weeks.',
  'welcome/g2': 'Lesson two is our history and leadership. More than one hundred and fifty years of daring to grow, a short timeline, and the people who lead Vanderbilt today: Chancellor Daniel Diermeier and the vice chancellors.',
  'welcome/g3': 'Lesson three is our mission, our students, and you. Six numbers that put the mission in perspective, a campus fun fact, and Vanderbilt quick facts.',
  'welcome/g4': 'Lesson four is the heart of the course: the four beliefs. Belonging, self-direction, collaboration, and growth. You will explore each one, practice it, and then use the belief compass to find the one that fits you best.',
  'welcome/g5': 'Lesson five is dare to grow. Our motto, crescere aude, and what it means as a mindset, with three situations to try it.',
  'welcome/g6': 'Lesson six is next steps. A short check of what you learned, four commitments, including a conversation with your manager, and an open invitation to visit us in Nashville.',
  'history/1': 'Lesson two. Our history. For more than one hundred and fifty years, Vanderbilt has been blazing trails, making transformative discoveries, and leading boldly. Start with the video to see our history come alive. Then tap each of the four moments below it to open it. On the next page, you can explore the full Vanderbilt timeline.',
  'timeline/1': 'Still in lesson two: the Vanderbilt timeline. At Vanderbilt, we take pride in our history, because it shapes our present and our future. The future is unwritten, and the present deserves our attention. Scroll through the timeline on this page to explore more than one hundred and fifty years of Vanderbilt, or open it in a full window. When you are ready, turn the page to meet our leadership.',
  'history/g1': 'Eighteen seventy three. Cornelius Vanderbilt gives one million dollars to found a university in Nashville. His hope was to strengthen the ties between all parts of the country. The university still carries his name.',
  'history/g2': 'Eighteen seventy five. Vanderbilt opens its doors to students. Since then, more than one hundred and seventy seven thousand degrees have been awarded. That is nearly one for every person in Chattanooga, Tennessee.',
  'history/g3': 'Twenty twenty. Daniel Diermeier becomes chancellor. He leads the safe return of students to campus during the COVID nineteen pandemic, puts the motto, dare to grow, at the center of the vision, and reaffirms Vanderbilt’s commitment to free expression and civil discourse.',
  'history/g4': 'And today, Vanderbilt is growing boldly. Research expenditures have passed one billion dollars, a capital campaign has succeeded, and the university now works from five cities.',
  'leaders/1': 'Still in lesson two: our leadership. Chancellor Daniel Diermeier was born in Berlin, Germany, and is a first generation college graduate who embodies Vanderbilt’s commitment to making an elite education accessible to all. Under his tenure, and in line with the motto crescere aude, dare to grow, Vanderbilt has passed one billion dollars in research expenditures, launched a successful capital campaign, and reaffirmed its commitment to free expression and civil discourse. He leads with a team of vice chancellors, each guiding a part of the university toward the mission: academic affairs, financial operations, and the culture and belonging of our staff, among others. Now try four statements. Fact, or fiction?',
  'numbers/1': 'Lesson three. Our mission, our students, and you. Vanderbilt’s rankings are important. But we are even more impressed by numbers like these, because they show the community you just joined, and the work that keeps it running. Six questions. Make your best guess on each, then read the story behind the number. And on the right, a fun fact about some of our smallest, furriest neighbors. The next page has the rest of the quick facts.',
  'facts/1': 'Still in lesson three: quick facts. For more than one hundred and fifty years, Vanderbilt has built a tradition of academic excellence along with a unique spirit of collaboration. Scroll through the quick facts on this page for the rest of the numbers, or open them in a full window. When you are ready, turn the page for lesson four, the four beliefs.',
  'beliefs/1': 'Lesson four. The four beliefs and the Vanderbilt Way. At Vanderbilt we offer more than an education: a journey of exceptional learning, opportunity, and experience. Four core beliefs guide it: belonging, self-direction, collaboration, and growth. They also guide how we work together. Open each belief to read what it means and the behaviors that show it, then apply it in a short moment. After all four, turn the page for your belief compass.',
  'beliefs/t1': 'Belonging. Once you’re chosen, you belong. Vanderbilt is intentionally very selective, and only people with the highest potential make the cut. Once you are here, you are surrounded by the best and brightest, brought together for one simple purpose: to improve each other. The behaviors: confident, never cutthroat. When you join, you commit. Respect the Vanderbilt Way. Create and cultivate conditions for success. Celebrate differences. And foster unity.',
  'beliefs/t2': 'Self-direction. Choose your own path, and go all in. Personal purpose is found through relentless exploration and challenge. If it is too comfortable, you are not doing it right. Experience as much as you can, and once you discover your path, give it everything you have. The behaviors: try, fail, learn, repeat. Embrace discomfort. Be ready to change your mind. Put in the work. No shortcuts. And prove the doubters wrong.',
  'beliefs/t3': 'Collaboration. Teams challenge and support each other. Our goal as a community is to work as one. By challenging and supporting one another, high functioning teams accomplish far more than individuals, and only by rallying around a common purpose can we multiply our individual potential. The behaviors: bands do more than soloists. Ditch the ego. See no boundaries. Pioneer together. Challenge directly. Respect the person. And redefine possible.',
  'beliefs/t4': 'Growth. We never stop growing and achieving. A permanent growth mindset matters more than any single achievement, however big. Human potential is realized over a lifetime, in increments and leaps, and it expands as you grow. The behaviors: growing the whole person. Obsessive self-improvement. In competition with yourself. Be the ladder for others. And lifelong leveling up.',
  'beliefs/m1': 'Here is a moment for belonging. It is your second week. In the team meeting, a colleague shares an idea that is quite different from how you would approach the problem, and the room goes quiet. What do you do?',
  'beliefs/m2': 'A moment for self-direction. Your manager asks who wants to lead a small project using a system nobody on the team knows well, including you. It would stretch you, and it would be uncomfortable. What do you do?',
  'beliefs/m3': 'A moment for collaboration. Someone from another department asks for help with a problem that is not technically your team’s job. You have the knowledge to help, and a busy week. What do you do?',
  'beliefs/m4': 'A moment for growth. You get feedback on your first project: the work is solid, and the way you presented it was hard to follow. It stings a little. What do you do?',
  'compass/1': 'Still in lesson four: your belief compass. You will live all four beliefs here. This page helps you find the one that sounds most like you right now. Four questions, and there are no wrong answers. Pick the answer that fits you best. Your compass will point to one belief. Then write a sentence or two about how you will embody it at work. You will bring that to your manager in lesson six.',
  'compass/belonging': 'Your compass points to belonging. Once you’re chosen, you belong. You care about the people around you, and about making Vanderbilt feel like home for everyone. Start with two behaviors: confident, never cutthroat, and when you join, you commit.',
  'compass/selfdir': 'Your compass points to self-direction. Choose your own path, and go all in. You are drawn to the challenge, and you finish what you choose. Start with two behaviors: try, fail, learn, repeat, and embrace discomfort.',
  'compass/collab': 'Your compass points to collaboration. Teams challenge and support each other. You do your best work with other people. Start with two behaviors: bands do more than soloists, and ditch the ego.',
  'compass/growth': 'Your compass points to growth. We never stop growing and achieving. You measure yourself against who you were yesterday. Start with two behaviors: growing the whole person, and obsessive self-improvement.',
  'grow/1': 'Lesson five. Dare to grow. Vanderbilt’s motto is crescere aude, Latin for dare to grow. It is more than a motto; it is a mindset. Adopt a growth mindset, because ability grows with effort. Use what is here: mentors, programs, courses, and your manager. And grow together, because growth at Vanderbilt is a team sport. Now try three situations. Pick the response you would give, then try the other two.',
  'grow/s1': 'Situation one. Your team uses a system you have never seen. Everyone else moves through it fast, and you have a report due in it on Friday. What do you do?',
  'grow/s2': 'Situation two. You sent an email to the wrong list. It is not a disaster, but a few people noticed. What do you do?',
  'grow/s3': 'Situation three. A colleague who started a month after you is stuck on something you figured out last week. What do you do?',
  'quiz/1': 'Lesson six begins with a quick check. Five questions, one at a time. Four of five finishes the check, and you can retake it anytime. Each answer tells you why.',
  'nextstep/1': 'Now, your next steps. We covered a lot in this course, and there is more to do. These tasks lock in what you learned and set you up for what comes next. Read and agree to each one. Discuss with your manager which belief you align with most, and how it will guide how you show up to work. Work with your manager to put your development plan into action. Complete your required compliance education. And finish your other tasks, including the Benefits Information Course and the Vanderbilt Voyage Day One Survey. Then copy the message to your manager, and send it today. And if you are ever in Nashville, join us for the full in-person Voyage, a campus tour, or just lunch. Email People, Culture and Belonging at p c b at vanderbilt dot e d u.',
  'learn/1': 'That is the course. Thank you for your attention, and welcome to Vanderbilt. The links from every lesson are on this page, to come back to in your first weeks. Take the Vanderbilt Voyage Day One Survey before you go. And remember, daring to grow is a powerful step toward your full potential. Crescere aude.'
};
